### ISSUE TITLE
Flaky Tests

### ISSUE THREAD

**Issue by mgodave** [twitter/distributedlog#15]
`Tests in error:
  testBadVersionOnTwoAllocators(com.twitter.distributedlog.bk.TestLedgerAllocator)
  testSuccessAllocatorShouldDeleteUnusedledger(com.twitter.distributedlog.bk.TestLedgerAllocator)`

**Comment by sijie** [comment]
Jiras are open in https://issues.apache.org/jira/browse/DL. Closed the issue here.
