### ISSUE TITLE
Flaky test (needs to bind to specific port)

### ISSUE THREAD

**Issue by mgodave** [twitter/distributedlog#17]
testCreateStreamTwice(com.twitter.distributedlog.service.TestDistributedLogServer): Failed to bind to: 0.0.0.0/0.0.0.0:7002

**Comment by mgodave** [comment]
https://travis-ci.org/twitter/distributedlog/builds/129791292

**Comment by sijie** [comment]
@mgodave going to close the issues in twitter repo. I've created corresponding DL jiras in apache. is that okay?
