### ISSUE TITLE
Publish jars to the Maven Central Repository

### ISSUE THREAD

**Issue by yjshen** [twitter/distributedlog#20]

**Comment by sijie** [comment]
@yjshen I published the jars to be hosted by the github repo for right now, as we might go to apache incubator soon where we might change a bit on how we make releases.

https://github.com/twitter/distributedlog/tree/mvn-repo

You could use add this to your pom.xml and use 0.3.51-RC1 as the version.

+    <repositories>
+    <repository>
+      <id>distributedlog-github-mvn-repo</id>
+      <url>https://raw.github.com/twitter/distributedlog/mvn-repo/${distributedlog.version}</url>
+      <snapshots>
+        <enabled>true</enabled>
+        <updatePolicy>always</updatePolicy>
+      </snapshots>
+    </repository>
+    </repositories>

**Comment by sijie** [comment]
I probably should create a page on how client can integrate with DL

**Comment by yjshen** [comment]
OK, I'll try it out. 
BTW, you haven't finished uploading jars yet? I didn't see `dl-service` jar for now.

**Comment by yjshen** [comment]
Would you please also include `sources.jar` if possible?

**Comment by sijie** [comment]
sources.jar are included. seems I am unable to upload distributedlog-service. will follow up.

**Comment by sijie** [comment]
@yjshen I just published the jars to http://central.sonatype.org. so the artifact should show up in central soon.

**Comment by yjshen** [comment]
OK, got it. 👍
