### ISSUE TITLE
Make MultiReader available in distributedlog-core

### ISSUE THREAD

**Issue by xiliuant** [twitter/distributedlog#23]
Reading from multiple log streams is extremely helpful for users. Could you make the 'MultiReader' in 'distributedlog-basic' tutorial a first class in 'distributedlog-core' module?

**Comment by sijie** [comment]
@xiliuant I've create the jira https://issues.apache.org/jira/browse/DL-8. let's move the work to apache. and I am going to close this issue here. is that okay?

**Comment by xiliuant** [comment]
@sijie sounds good to me.
