### ISSUE TITLE
Would you please help explain more for the IDs of a record?

### ISSUE THREAD

**Issue by jiazhai** [twitter/distributedlog#28]
Would you please help explain more for the Figure 2 of the [introduction](http://distributedlog.io/html/basics/introduction.html) ？

> in Figure 2, 
> at the top-left, there is a word LSSN, which may be "Log Segment Sequence Number", not explicted explained. 
> at the top-right, there are 3 word "DLSN", "Sequence ID", "Transaction ID" next to "record 1". This seems like each record has these 3 IDs. While, By reading the introduction, there seems each record has 2 ID,  both "DLSN" and "Transaction ID" that could served as a "Sequence ID".

And here is Sijie Guo's answers for above questions in google groups:

> Yes. there are 3 ID associated with a record.
> Transaction ID: application provided sequence number. it is usually timestamp.
> DLSN: Distributed Log Sequence Number. It is system generated sequence number. It is typically used for fast looking up, positioning and truncation. It is comprised with LSSN (Log Segment Sequence Number), Entry Id and Slot Id. It can be used to determine the ordering of two records. 
> SequenceID is an monotonically increasing long number starting from 0. Applications can tell how many records between two records by just comparing their sequence ids.

**Comment by sijie** [comment]
@jiazhai I've created https://issues.apache.org/jira/browse/DL-11 let's track in apache jira. I am going to close the issue here. is that okay?

**Comment by sijie** [comment]
DL-11 is used for tracking this. Closed the issue here.
