### ISSUE TITLE
broken quickstart tutorial

### ISSUE THREAD

**Issue by bptinsley** [twitter/distributedlog#40]
parameters passed when running dlog-daemon.sh are ignored and default hardcoded parameters are used instead. see - http://distributedlog.io/basics/quickstart.html

**Comment by sijie** [comment]
@bptinsley you are right. good catch! do you want to send a pull request for this fix :) ?

**Comment by sijie** [comment]
@bptinsley we moved the development to apache incubator. I created a jira for it : https://issues.apache.org/jira/browse/DL-24

**Comment by crazysoftwarecoder** [comment]
@sijie - It seems to me that the quickstart works perfectly if I download 0.3.51-RC0. But if I download 0.3.51-RC1 then the current quickstart document breaks especially in the place where it starts a write proxy. There is no file called as ./distributedlog-service/conf/distributedlog_proxy.conf in RC1 I believe.

**Comment by sijie** [comment]
@crazysoftwarecoder Ah, I see. It seems that I moved the distributedlog_proxy.conf to write_proxy.conf in this change (https://github.com/twitter/distributedlog/commit/9f57667c7e35a67b839bd4bada1c02bad09bfbb7). Do you want to make a contribution to fix it?

**Comment by crazysoftwarecoder** [comment]
@sijie - Sure. Change the documentation or revert that file name in code?

**Comment by sijie** [comment]
@crazysoftwarecoder let's fix the documentation. does that sound good?

**Comment by crazysoftwarecoder** [comment]
Sure @sijie - I did some more analysis and found out that the dlog-daemon.sh does not respect the parameters that the command line sends in:

localhost:Downloads asfernando$ ./distributedlog-service/bin/dlog-daemon.sh start writeproxy -p 8000 --shard-id 1 -sp 8001 -u distributedlog://127.0.0.1:7000/messaging/my_namespace -mx -c `pwd`/distributedlog-service/conf/write_proxy.conf
doing start writeproxy ...
starting writeproxy, logging to /Users/asfernando/Downloads/distributedlog-service/logs/dlog-writeproxy-localhost-4181.log
Service args --conf /Users/asfernando/Downloads/distributedlog-service/conf/write_proxy.conf --uri distributedlog://127.0.0.1:2181/messaging/distributedlog/mynamespace --shard-id 0 --port 4181 --stats-port 9000 --stats-provider org.apache.bookkeeper.stats.CodahaleMetricsServletProvider --announce --thriftmux
JMX enabled by default

Printing serviceargs shows that the defaults are chosen all the time. Is this how you intend this to be, or are you accepting command line overrides as well for RC1? Please let me know and I will take a look at the fix.

**Comment by sijie** [comment]
@crazysoftwarecoder 

after RC1, we made to use same dlog-daemon.sh be able to start zookeeper, bookie or write proxy. the change was made to not accept overrides from command line, rather than using overrides in conf/dlogenv.sh.

so the `dlog-daemon.sh start writeproxy` command in QuickStart page might need to be changed. (http://distributedlog.io/operations/deployment.html#run-write-proxy has the command how to start a write proxy)

**Comment by crazysoftwarecoder** [comment]
Thanks @sijie. Its done. Shall I create the patch and attach it here?

**Comment by sijie** [comment]
@crazysoftwarecoder cool. Can you send the pull request to https://github.com/apache/incubator-distributedlog?

I put up a wiki page about github workflow: https://cwiki.apache.org/confluence/display/DL/Contributing+to+DistributedLog#ContributingtoDistributedLog-ContributingCodeChanges

Let me know if you have any questions.

**Comment by crazysoftwarecoder** [comment]
Done - https://github.com/apache/incubator-distributedlog/pull/17

**Comment by sijie** [comment]
Awesome. Thank you @crazysoftwarecoder

**Comment by crazysoftwarecoder** [comment]
@sijie - np. I am onboarding the community of distributed log currently. If you have any noob issues, please send them over. Thanks for your help. I will also look at the jira board and take up issues as I see fit.

**Comment by sijie** [comment]
Sure thing. 

Closing the pull request, since the pull request has been sent to incubator-distributedlog.
