### ISSUE TITLE
master building failed

### ISSUE THREAD

**Issue by tylaar** [twitter/distributedlog#42]
[ERROR] Failed to execute goal on project distributedlog-service: Could not resolve dependencies for project com.twitter:distributedlog-service:jar:0.3.51-SNAPSHOT: Could not find artifact com.twitter:distributedlog-core:jar:tests:0.3.51-SNAPSHOT in bookkeeper-twitter-mvn-repo (https://raw.github.com/twitter/bookkeeper/mvn-repo/4.3.5-TWTTR-OSS) -> [Help 1]

Looks like it's still a twitter maven dependency issue. 

Is there any plan about not depend on twitter's specific maven repo?

**Comment by sijie** [comment]
It doesn't seem to be a dependency problem. What command did you run?

Re "Twitter Maven Repo" - yup there are plans to not depend on twitters maven repo. You can follow the progress on https://issues.apache.org/jira/browse/DL/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel , since we already moved the development to Apache incubator.

**Comment by tylaar** [comment]
It's a simple mvn clean install -Dmaven.test.skip=true , and before that i am sure my m2/settings.xml are clean.

I found that master branch has this issue, and when I change to Release0.3.51-RC1, thing goes well. Anything special about master branch ?

**Comment by sijie** [comment]
@tylaar interesting. I try to build from master (I cleaned my local m2 repo) and I didn't see any problem.

Also, FYI. The project has been moved to Apache Incubator. https://github.com/apache/incubator-distributedlog Can you try building from there and let me know if it works or not?

**Comment by tylaar** [comment]
Hey sijie, I checked out the incubator repo, and mvn clean install -Dmaven.test.skip=true, and still get [ERROR] Failed to execute goal on project distributedlog-benchmark: Could not resolve dependencies for project com.twitter:distributedlog-benchmark:jar:0.4.0-incubating-SNAPSHOT: Could not find artifact com.twitter:distributedlog-core:jar:tests:0.4.0-incubating-SNAPSHOT in bookkeeper-twitter-mvn-repo (https://raw.github.com/twitter/bookkeeper/mvn-repo/4.3.5-TWTTR-OSS) -> [Help 1]

Since I don't need to run the test now, I did the trick to comment out two pom dependency in distributedlog-service and distributedlog-benchmark:
    <dependency>
      <groupId>com.twitter</groupId>
      <artifactId>distributedlog-core</artifactId>
      <version>${project.parent.version}</version>
      <scope>test</scope>
      <type>test-jar</type>
    </dependency>


After that everything goes well.

**Comment by sijie** [comment]
Interesting. This seems to be something related to mvn version. It seems that the tests jar wasn't installed at package phase. What maven version are you using?

**Comment by tylaar** [comment]
Hey sijie, I am using Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T08:41:47-08:00)

**Comment by sijie** [comment]
@tylaar hmm. I am using the same maven version. How does your ~/.m2/settings.xml look like?

> Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T08:41:47-08:00)

**Comment by tylaar** [comment]
I cleared that up ... no settings.xml which I think it means default settings.

**Comment by sijie** [comment]
closed this issue here. we moved the issue tracking to apache - https://issues.apache.org/jira/browse/DL
